version: '3'

services:
  mango:
    container_name: mango
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - 9000
    ports:
      - 9000:9000
    volumes:
      - ~/mango:/root/mango
      - ~/.config/mango:/root/.config/mango
